version: '3.9'
services:
  unifi:
    image: 'jacobalberty/unifi:latest'
    restart: always
    container_name: ct_unifi_controller
    ports:
      - '8080:8080'
      - '8443:8443'
      - '3478:3478'
      - '8843:8443'
      - '8880:8880'
      - '6789:6789'
    networks:
      - net
    volumes:
      - /volume1/docker/unifi/data:/unifi/data
      - /volume1/docker/unifi/log:/unifi/log

networks:
  net:
    driver: bridge
